### ISSUE TITLE
Can't install in 0.5.2 webui

### ISSUE THREAD

**Issue by btrepp** [vijaynalawade/flogo#1]
Fails to install and has the error message in logs

```
2018-03-23T06:59:55.814Z - info: run command: flogo install github.com/vijaynalawade/flogo/tree/master/activity/js
2018-03-23T07:00:17.547Z - warn: command exited with code 1: flogo install github.com/vijaynalawade/flogo/tree/master/activity/js

Solving failure: No versions of github.com/vijaynalawade/flogo met constraints:
        master: Could not introduce github.com/vijaynalawade/flogo@master, as its subpackage github.com/vijaynalawade/flogo/tree/master/activity/js is
 missing. (Package is required by (root).)
FATAL: command "install" failed: Error adding dependency 'github.com/vijaynalawade/flogo/tree/master/activity/js', 'exit status 1'

[error] add activities to test engine

Solving failure: No versions of github.com/vijaynalawade/flogo met constraints:
        master: Could not introduce github.com/vijaynalawade/flogo@master, as its subpackage github.com/vijaynalawade/flogo/tree/master/activity/js is
 missing. (Package is required by (root).)
FATAL: command "install" failed: Error adding dependency 'github.com/vijaynalawade/flogo/tree/master/activity/js', 'exit status 1'

2018-03-23T07:00:17.550Z - error:  Error: [error] Encounter error to add activities to test engine.
    at Object.installActivities (/tmp/flogo-web/build/server/api/activities/index.js:145:13)
    at installActivities.throw (<anonymous>)
    at onRejected (/tmp/flogo-web/build/server/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[log] Install Activities
[ 'github.com/vijaynalawade/flogo/activity/js' ]
[log] adding activities to test engine...
2018-03-23T07:02:16.061Z - error:  Error: [error] Encounter error to stop test engine.
    at Object.installActivities (/tmp/flogo-web/build/server/api/activities/index.js:131:13)
    at installActivities.next (<anonymous>)
    at onFulfilled (/tmp/flogo-web/build/server/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by fcastill** [comment]
The ref/url to use in the UI should be the same as the one for the CLI, it should be: `github.com/vijaynalawade/flogo/activity/js` (without the /tree/master portion)

**Comment by JGrotex** [comment]
The issue should be solved with this hint from 'fcastill'.
